const products = [
    {
        id: 1,
        title: "Cinematic Transitions Pack",
        description: "20 professional transitions for Premiere Pro.",
        price: 29.99,
        oldPrice: 49.99,
        image: "https://via.placeholder.com/400x225/0071e3/ffffff?text=Cinematic+Transitions",
        previewVideo: "assets/previews/cinematic-transitions.mp4",
        gallery: [
            "assets/previews/transition-1.mp4",
            "assets/previews/transition-2.mp4",
            "assets/previews/transition-3.mp4"
        ],
        features: ["20 unique transition presets", "Works with Premiere Pro CC 2018+", "4K resolution support", "Easy to customize colors and timing", "Includes tutorial video"],
        category: "transitions",
        rating: 4.7,
        reviews: 128
    },
    {
        id: 2,
        title: "Modern Titles Collection",
        description: "15 animated titles for your projects.",
        price: 24.99,
        oldPrice: 39.99,
        image: "https://via.placeholder.com/400x225/ff2d55/ffffff?text=Modern+Titles",
        previewVideo: "path/to/your/video2.mp4",
        gallery: [],
        features: ["15 animated titles", "Fully customizable", "Modern design"],
        category: "titles",
        rating: 4.9,
        reviews: 98
    },
    {
        id: 3,
        title: "Color Grading Presets",
        description: "10 LUTs for professional color grading.",
        price: 19.99,
        oldPrice: 29.99,
        image: "https://via.placeholder.com/400x225/34c759/ffffff?text=Color+Presets",
        previewVideo: "path/to/your/video3.mp4",
        gallery: [],
        features: ["10 professional LUTs", "Works in any editor", "Instant results"],
        category: "presets",
        rating: 4.6,
        reviews: 150
    },
    {
        id: 4,
        title: "Special Effects Bundle",
        description: "30+ effects for After Effects.",
        price: 39.99,
        oldPrice: 59.99,
        image: "https://via.placeholder.com/400x225/5856d6/ffffff?text=Special+Effects",
        previewVideo: "path/to/your/video4.mp4",
        gallery: [],
        features: ["30+ VFX elements", "After Effects CC", "Drag and drop"],
        category: "effects",
        rating: 4.8,
        reviews: 210
    },
    {
        id: 5,
        title: "Social Media Pack",
        description: "Templates for Instagram, TikTok, YouTube.",
        price: 27.99,
        oldPrice: 44.99,
        image: "https://via.placeholder.com/400x225/ff9500/ffffff?text=Social+Media",
        previewVideo: "path/to/your/video5.mp4",
        gallery: [],
        features: ["Instagram Stories", "TikTok templates", "YouTube Endscreens"],
        category: "bundles",
        rating: 4.7,
        reviews: 180
    },
    {
        id: 6,
        title: "Minimal Lower Thirds",
        description: "Clean and modern lower thirds for any video.",
        price: 17.99,
        oldPrice: 24.99,
        image: "https://via.placeholder.com/400x225/ffcc00/ffffff?text=Lower+Thirds",
        previewVideo: "path/to/your/video6.mp4",
        gallery: [],
        features: ["10 lower thirds", "Easy to edit", "Minimalist design"],
        category: "titles",
        rating: 4.9,
        reviews: 75
    }
];